version: '3.8'
services:
    app:
        container_name: ${APP_CONTAINER_NAME}
        build:
            context: .
        ports:
            - ${APP_PORT}:3000
        restart: unless-stopped
        volumes:
            - ./uploads:/usr/app/uploads:rw
        links:
            - mongo
        depends_on:
            - mongo
    mongo:
        image: mongo:latest
        container_name: ${MONGODB_CONTAINER_NAME}
        environment:
            - MONGO_INITDB_DATABASE=${DATABASE_NAME}
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
        volumes:
            - ${DATABASE_VOLUME_MOUNT}:/data/db
        restart: unless-stopped
        command: [ --auth ]
