export const BC_CONNECTION_API = {
    INVOKE_BC: '/api/v1/bc-transaction/invoke',
    QUERY_BC: '/api/v1/bc-transaction/query',
    REGISTER_USER: '/api/v1/bc-user/register',
    ACTIVATE_USER: '/api/v1/user/activate',
    DEACTIVATE_USER: '/api/v1/user/deactivate',
    CHECK_USER: '/api/v1/user/check',
    REGISTER_SUPER_ADMIN_USER: '/api/v1/bc-user/registerSuperAdmin',
    CHECK_BC_NODE_CONNECTION: '/api/v1/connection',
    CHECK_BC_NODE_AUTHENTICATION: '/api/v1/connection/check-authentication',
    PROJECT_BC: '/api/v1/project',
    GET_PROJECT_BC_HISTORY: '/api/v1/project/history',
    PROJECT_VERSION_BC: '/api/v1/model-version',
    PROJECT_VERSION_BC_HISTORY: '/api/v1/model-version/history',
    MODEL_VERSION_BC: '/api/v1/model-review',
    MODEL_VERSION_BC_HISTORY: '/api/v1/model-review/history',
    STORE_MODEL_EXPERIMENT_BC: '/api/v1/model-experiment',
    GET_MODEL_BC_EXPERIMENT_DETAILS: '/api/v1/model-experiment/get',
    GET_MODEL_BC_EXPERIMENT_HISTORY: '/api/v1/model-experiment/history',
    STORE_ARTIFACT_MODEL_BC: '/api/v1/model-artifact',
    GET_ARTIFACT_MODEL_BC_DETAILS: '/api/v1/model-artifact/get',
    GET_ARTIFACT_MODEL_BC_HISTORY: '/api/v1/model-artifact/history'
};
