export const MANAGE_PROJECT_BC_CONSTANT = {
    UNABLE_TO_GET_PROJECT_BC_DETAILS: 'UNABLE_TO_GET_PROJECT_BC_DETAILS',
    PROJECT_BC_DETAILS_RETRIEVED_SUCCESS: 'PROJECT_BC_DETAILS_RETRIEVED_SUCCESS',
    UNABLE_TO_FETCH_PROJECT_BC_HISTORY: 'UNABLE_TO_FETCH_PROJECT_BC_HISTORY',
    PROJECT_BC_HISTORY_FETCHED_SUCCESS: 'PROJECT_BC_HISTORY_FETCHED_SUCCESS',
    UNABLE_TO_GET_PROJECT_VERSION_BC_DETAILS: 'UNABLE_TO_GET_PROJECT_VERSION_BC_DETAILS',
    PROJECT_VERSION_BC_DETAILS_RETRIEVED_SUCCESS: 'PROJECT_VERSION_BC_DETAILS_RETRIEVED_SUCCESS',
    UNABLE_TO_FETCH_PROJECT_VERSION_BC_HISTORY: 'UNABLE_TO_FETCH_PROJECT_VERSION_BC_HISTORY',
    PROJECT_VERSION_BC_HISTORY_FETCHED_SUCCESS: 'PROJECT_VERSION_BC_HISTORY_FETCHED_SUCCESS',
    UNABLE_TO_GET_MODEL_REVIEW_BC_DETAILS: 'UNABLE_TO_GET_MODEL_REVIEW_BC_DETAILS',
    MODEL_REVIEW_BC_DETAILS_RETRIEVED_SUCCESS: 'MODEL_REVIEW_BC_DETAILS_RETRIEVED_SUCCESS'
};
