export const BC_PAYLOAD = {
    CREATE_VACCINATION: 'Create New Vaccination',
    UPDATE_VACCINATION: 'Update Vaccination',
    CREATE_VACCINE_CARD: 'Create New Vaccine Card',
    UPDATE_VACCINE_CARD: 'Update Vaccine Card',
    CREATE_USER: 'Create New User',
    UPDATE_USER: 'Update User',
    UPDATE_SUBSCRIPTION: 'Update Subscription',
    CREATE_VACCINE_OUTREACH: 'Create Vaccine Outreach',
    UPDATE_VACCINE_OUTREACH: 'Update Vaccine Outreach',
    TRANSFER_TO_CASE: 'Transfer To Case',
    TRANSFER_TO_MAIN_CASE: 'Transfer To Main Case',
    VACCINE_OUTREACH_ADD_TO_CASE: 'Vaccine Outreach Add To Case',
    UPDATE_VACCINE_OUTREACH_FROM_WORKFLOW: 'Update Vaccine Outreach From Workflow',
    CREATE_VACCINE_WORKFLOW: 'Create Vaccine Workflow',
    UPDATE_VACCINE_WORKFLOW: 'Update Vaccine Workflow',
    CREATE_VACCINE_WORKFLOW_FROM_SUBJECT: 'Create Vaccine Workflow From Subject',
    UPDATE_VACCINE_WORKFLOW_FROM_SUBJECT: 'Update Vaccine Workflow From Subject',
    CREATE_CASE_WORKFLOW: 'Create Case Workflow',
    UPDATE_CASE_WORKFLOW: 'Update Case Workflow',
    CREATE_CASE_WORKFLOW_FROM_CASE: 'Create Case Workflow From Case',
    UPDATE_CASE_WORKFLOW_FROM_CASE: 'Update Case Workflow From Case',
    CREATE_CASE: 'Create New Case',
    TRANSFER_TO_CASE_FROM_WORK_SAFE: 'Transfer To Case From Work Safe',
    UPDATE_CASE: 'Update Case',
    UPDATE_CASE_FROM_WORKFLOW: 'Update Case From Workflow',
    UPDATE_CASE_FROM_VACCINE_OUTREACH: 'Update Case From Vaccine',
    UPDATE_VACCINE_OUTREACH_FROM_CASE: 'Update Vaccine From Case',
    CREATE_CASE_FROM_VACCINE_OUTREACH: 'Create New Case From Vaccine',
    UPDATE_CASE_FROM_WORK_SAFE: 'Update Case From Work Safe',
    UPDATE_VACCINE_OUTREACH_FROM_WORK_SAFE: 'Update Vaccine Outreach From Work Safe',
    CREATE_COHORT: 'Create New Cohort',
    UPDATE_COHORT: 'Update Cohort',
    CREATE_SPONSOR_ITEM: 'Create Sponsor Item',
    UPDATE_SPONSOR_ITEM: 'Update Sponsor Item',
    UPDATE_SPONSOR_ITEM_FROM_TRAINEE: 'Update Sponsor Item From Trainee',
    DELETE_SPONSOR_ITEM: 'Delete Sponsor Item',
    CREATE_SPONSOR_TRAINEE: 'Create Sponsor Trainee',
    UPDATE_SPONSOR_TRAINEE: 'Update Sponsor Trainee',
    CREATE_ASSESSMENT: 'Create Assessment',
    UPDATE_ASSESSMENT: 'Update Assessment',
    CREATE_TRAINING_NOTE: 'Create Training Note',
    UPDATE_TRAINING_NOTE: 'Update Training Note',
    CREATE_EDUCATION: 'Create Education',
    UPDATE_EDUCATION: 'Update Education',
    DELETE_EDUCATION: 'Delete Education',
    CREATE_LANGUAGE: 'Create Language',
    UPDATE_LANGUAGE: 'Update Language',
    DELETE_LANGUAGE: 'Delete Language',
    CREATE_SKILL: 'Create Skill',
    UPDATE_SKILL: 'Update Skill',
    DELETE_SKILL: 'Delete Skill',
    CREATE_EXPERIENCE: 'Create Experience',
    UPDATE_EXPERIENCE: 'Update Experience',
    DELETE_EXPERIENCE: 'Delete Experience',
    ADD_EDUCATION: 'Add Education',
    REMOVE_EDUCATION: 'Remove Education',
    ADD_EXPERIENCE: 'Add Experience',
    REMOVE_EXPERIENCE: 'Remove Experience',
    ADD_SKILL: 'Add Skill',
    ADD_LANGUAGE: 'Add Language',
    CREATE_CASE_NOTE: 'Create Case Note',
    UPDATE_CASE_NOTE: 'Update Case Note',
    CREATE_VACCINE_OUTREACH_NOTE: 'Create Vaccine Outreach Note',
    UPDATE_VACCINE_OUTREACH_NOTE: 'Update Vaccine Outreach Note',
    CREATE_TRAINEE_ASSESSMENT: 'Create Trainee Assessment',
    UPDATE_TRAINEE_ASSESSMENT_BY_INSTRUCTOR: 'Update Trainee Assessment By Instructor',
    UPDATE_TRAINEE_ASSESSMENT_BY_TRAINEE: 'Update Trainee Assessment By Trainee',
    ENABLE_USER: 'Enable User',
    DISABLE_USER: 'Disable User',
    ENABLE_VACCINATION: 'Enable Vaccination',
    DISABLE_VACCINATION: 'Disable Vaccination',
    CREATE_ORGANIZATION: 'Create Organization',
    UPDATE_ORGANIZATION: 'Update Organization',
    CREATE_ANSWER: 'Create Answer',
    CREATE_QUESTION: 'Create Question',
    UPDATE_QUESTION: 'Update Question',
    CREATE_WORK_SAFE_EMPLOYEE: 'Create Participant',
    ADD_CASE_NO_ON_WORK_SAFE_EMPLOYEE: 'Add Case No on Work Safe',
    UPDATE_WORK_SAFE_EMPLOYEE: 'Update Participant',
    ENABLE_WORK_SAFE_EMPLOYEE: 'Enable Participant',
    DISABLE_WORK_SAFE_EMPLOYEE: 'Disable Participant',
    CREATE_WORK_SAFE_BATCH: 'Create Work Safe Batch',
    UPDATE_WORK_SAFE_BATCH: 'Update Work Safe Batch',
    CREATE_WORK_SAFE_CONFIG: 'Create Work Safe Config',
    UPDATE_WORK_SAFE_CONFIG: 'Update Work Safe Config',
    DISABLE_WORK_SAFE_CONFIG: 'Disable Work Safe Config',
    ENABLE_WORK_SAFE_CONFIG: 'Enable Work Safe Config',
    CREATE_WORK_SAFE_TEST_RESULT: 'Create Work Safe Test Result',
    UPDATE_WORK_SAFE_TEST_RESULT: 'Update Work Safe Test Result',
    DISABLE_WORK_SAFE_TEST_RESULT: 'Disable Work Safe Test Result',
    ENABLE_WORK_SAFE_TEST_RESULT: 'Enabled Work Safe Test Result',
    MIGRATION_SUCCESS: 'Migration Successful',
    ADD_CASE_TO_VACCINE_OUTREACH: 'Add Case To Vaccine Outreach',
    CREATE_WORK_SAFE_QUARANTINE: 'Create Work Safe Quarantine',
    CREATE_WORK_SAFE_QUARANTINE_FROM_FILE: 'Create Work Safe Quarantine From File',
    UPDATE_WORK_SAFE_QUARANTINE: 'Update Work Safe Quarantine',
    WORK_SAFE_QUARANTINE_EXITED: 'Work Safe Quarantine Exited',
    CREATE_COMPANY_BRANCH: 'Create Organization Division',
    UPDATE_COMPANY_BRANCH: 'Update Organization Division',
    ENABLE_COMPANY_BRANCH: 'Enable Organization Division',
    DISABLE_COMPANY_BRANCH: 'Disable Organization Division',
    CREATE_WORK_SAFE_TYPE: 'Create Work Safe Type',
    UPDATE_WORK_SAFE_TYPE: 'Update Work Safe Type',
    ENABLE_WORK_SAFE_TYPE: 'Enable Work Safe Type',
    DISABLE_WORK_SAFE_TYPE: 'Disable Work Safe Type',
    ADD_FOLLOW_UP_DATE: 'Added Follow Up Date',
    CREATE_WORK_SAFE_GUARDIAN: 'Create Work Safe Guardian',
    UPDATE_WORK_SAFE_GUARDIAN: 'Update Work Safe Guardian',
    ENABLE_WORK_SAFE_GUARDIAN: 'Enable Work Safe Guardian',
    DISABLE_WORK_SAFE_GUARDIAN: 'Disable Work Safe Guardian',
    CREATE_TRIAND_CONFIG: 'Create Triand Config',
    UPDATE_TRIAND_CONFIG: 'Update Triand Config',
    ENABLE_TRIAND_CONFIG: 'Enable Triand Config',
    DISABLE_TRIAND_CONFIG: 'Disable Triand Config'
};
