export const CHANNEL_DETAIL = {
    SUCCESSFULLY_ADDED_CHANNEL_DETAIL: 'SUCCESSFULLY_ADDED_CHANNEL_DETAIL',
    SUCCESSFULLY_UPDATED_CHANNEL_DETAIL: 'SUCCESSFULLY_UPDATED_CHANNEL_DETAIL',
    SUCCESSFULLY_DELETED_CHANNEL_DETAIL: 'SUCCESSFULLY_DELETED_CHANNEL_DETAIL',
    FETCHED_ALL_CHANNEL_DETAIL: 'FETCHED_ALL_CHANNEL_DETAIL',
    FETCHED_CHANNEL_DETAIL: 'FETCHED_CHANNEL_DETAIL',
    CHANNEL_DETAIL_NOT_FOUND: 'CHANNEL_DETAIL_NOT_FOUND',
    CHANNEL_DETAIL_ALREADY_EXISTS: 'CHANNEL_DETAIL_ALREADY_EXISTS',
    DEFAULT_CHANNEL_DETAIL_ALREADY_EXISTS: 'DEFAULT_CHANNEL_DETAIL_ALREADY_EXISTS',
    DEFAULT_CHANNEL_DETAIL_NOT_FOUND: 'DEFAULT_CHANNEL_DETAIL_NOT_FOUND',
    FETCHED_DEFAULT_CHANNEL_DETAIL: 'FETCHED_DEFAULT_CHANNEL_DETAIL',
    FETCHED_ALL_NON_DEFAULT_CHANNEL_DETAILS: 'FETCHED_ALL_NON_DEFAULT_CHANNEL_DETAILS',
    CHANNEL_ID_NOT_FOUND: 'CHANNEL_ID_NOT_FOUND'
};
