export const CHANNEL_MAPPING = {
    SUCCESSFULLY_ADDED_CHANNEL_MAPPING: 'SUCCESSFULLY_ADDED_CHANNEL_MAPPING',
    SUCCESSFULLY_UPDATED_CHANNEL_MAPPING: 'SUCCESSFULLY_UPDATED_CHANNEL_MAPPING',
    SUCCESSFULLY_DELETED_CHANNEL_MAPPING: 'SUCCESSFULLY_DELETED_CHANNEL_MAPPING',
    CHANNEL_MAPPING_NOT_FOUND: 'CHANNEL_MAPPING_NOT_FOUND',
    CHANNEL_MAPPING_ALREADY_EXISTS: 'CHANNEL_MAPPING_ALREADY_EXISTS',
    FETCHED_CHANNEL_MAPPING: 'FETCHED_CHANNEL_MAPPING',
    SUCCESSFULLY_ADDED_SUPER_ADMIN_CHANNEL_MAPPING: 'SUCCESSFULLY_ADDED_SUPER_ADMIN_CHANNEL_MAPPING'
};
