version: '3.8'
services:
    app:
        image: bta-api-dev:1.0.0
        build:
            target: production
        command: npm run start:prod
        volumes:
            - bta_nodemodules:/usr/app/node_modules
        links:
            - mailcatcher
        depends_on:
            - mailcatcher

    mailcatcher:
        image: sj26/mailcatcher
        container_name: ${MAILCATCHER_CONTAINER_NAME}
        ports:
            - ${MAILCATCHER_PORT}:1080
volumes:
    bta_nodemodules:
