version: '3.8'
services:
    app:
        image: bta-api-prod:1.0.0
        build:
            target: production
            args:
                UID: ${USER_ID}
                GID: ${GROUP_ID}
        command: npm run start:prod
