export const BC_NODE_INFO_CONSTANT = {
    BC_NODE_INFO_ALREADY_EXISTS: 'BC_NODE_INFO_ALREADY_EXISTS',
    BC_NODE_INFO_ADD_FAILED: 'BC_NODE_INFO_ADD_FAILED',
    BC_NODE_INFO_UPDATE_FAILED: 'BC_NODE_INFO_UPDATE_FAILED',
    BC_NODE_INFO_ADDED: 'BC_NODE_INFO_ADDED',
    INCORRECT_BC_NODE_INFO: 'INCORRECT_BC_NODE_INFO',
    BC_NODE_INFO_NOT_FOUND: 'BC_NODE_INFO_NOT_FOUND',
    FETCHED_ALL_BC_NODE_INFO: 'FETCHED_ALL_BC_NODE_INFO',
    BC_NODE_INFO_UPDATED: 'BC_NODE_INFO_UPDATED',
    BC_NODE_INFO_DELETE_FAILED: 'BC_NODE_INFO_DELETE_FAILED',
    BC_NODE_INFO_DELETED: 'BC_NODE_INFO_DELETED'
};
