export const BLOG_CONSTANT = {
    NEW_BLOG_CREATED: 'NEW_BLOG_CREATED',
    FAILED_TO_ADD_NEW_BLOG: 'FAILED_TO_ADD_NEW_BLOG',
    BLOG_DETAIL_FOUND: 'BLOG_DETAIL_FOUND',
    CANNOT_GET_BLOG: 'CANNOT_GET_BLOG',
    BLOGS_LIST_FOUND: 'BLOGS_LIST_FOUND',
    CANNOT_GET_BLOGS: 'CANNOT_GET_BLOGS',
    BLOG_DELETED: 'BLOG_DELETED',
    CANNOT_DELETE_BLOG: 'CANNOT_DELETE_BLOG',
    BLOG_UPDATED: 'BLOG_UPDATED',
    BLOG_URL_HAS_ALREADY_BEEN_USED: 'BLOG_URL_HAS_ALREADY_BEEN_USED', //Old format (`${blog.url} has already been used`)
    REQUESTED_BLOG_CANNOT_BE_FOUND: 'REQUESTED_BLOG_CANNOT_BE_FOUND',
    UPDATE_BLOG_FAILED: 'UPDATE_BLOG_FAILED'
};
