export const COMMON_ERROR = {
    COMPANYNAME_HAS_ALREADY_BEEN_REGISTERED: 'COMPANYNAME_HAS_ALREADY_BEEN_REGISTERED',
    BAD_REQUEST: 'BAD_REQUEST',
    DELETE_SUCCESS: 'DELETE_SUCCESS',
    DELETE_FAILED: 'DELETE_FAILED',
    SEARCH_RESULT_FOUND: 'SEARCH_RESULT_FOUND',
    SEARCH_RESULT_NOT_FOUND: 'SEARCH_RESULT_NOT_FOUND',
    DATA_NOT_FOUND: 'DATA_NOT_FOUND',
    FAILED_TO_CREATE: 'FAILED_TO_CREATE',
    FAILED_TO_UPDATE: 'FAILED_TO_UPDATE',
    ALREADY_CREATED: 'ALREADY_CREATED',
    ENABLE_SUCCESS: 'ENABLE_SUCCESS',
    SOMETHING_WENT_WRONG: 'SOMETHING WENT WRONG',
    UNAUTHORIZED_TO_ACCESS: 'UNAUTHORIZED_TO_ACCESS',
    UNVERIFIED_REQUEST: 'UNVERIFIED_REQUEST'
};

export const MONGO_SCHEMA_ERROR_CODE = {
    DUPLICATE_KEY: 11000
};
