export const COMPANY_TRANSFER_CONSTANT = {
    COMPANY_TRANSFER_DATA_NOT_FOUND: 'COMPANY_TRANSFER_DATA_NOT_FOUND',
    TRANSFER_TOKEN_EXPIRED_OR_INVALID: 'TRANSFER_TOKEN_EXPIRED_OR_INVALID',
    COMPANY_NOT_FOUND: 'COMPANY_NOT_FOUND',
    CANNOT_REFRESH_COMPANY_TRANSFER: 'CANNOT_REFRESH_COMPANY_TRANSFER',
    SUCCESSFULLY_REFRESH_COMPANY_TRANSFER: 'SUCCESSFULLY_REFRESH_COMPANY_TRANSFER',
    FETCHED_COMPANY_TRANSFER_DATA_BY_TOKEN_SUCCESSFULLY: 'FETCHED_COMPANY_TRANSFER_DATA_BY_TOKEN_SUCCESSFULLY'
};
