export const COMPANY_BRANCH_CONSTANT = {
    SUCCESSFULLY_CREATED_COMPANY_BRANCH: 'SUCCESSFULLY_CREATED_COMPANY_BRANCH',
    FAILED_TO_CREATE_COMPANY_BRANCH: 'FAILED_TO_CREATE_COMPANY_BRANCH',
    SUCCESSFULLY_FETCHED_COMPANY_BRANCH: 'SUCCESSFULLY_FETCHED_COMPANY_BRANCH',
    COMPANY_BRANCH_NOT_FOUND: 'COMPANY_BRANCH_NOT_FOUND',
    SUCCESSFULLY_UPDATED_COMPANY_BRANCH: 'SUCCESSFULLY_UPDATED_COMPANY_BRANCH',
    FAILED_TO_UPDATE_COMPANY_BRANCH: 'FAILED_TO_UPDATE_COMPANY_BRANCH',
    COMPANY_BRANCH_DISABLED: 'COMPANY_BRANCH_DISABLED',
    FAILED_TO_DISABLE_COMPANY_BRANCH: 'FAILED_TO_DISABLE_COMPANY_BRANCH',
    COMPANY_BRANCH_ENABLED: 'COMPANY_BRANCH_ENABLED',
    COMPANY_BRANCH_ALREADY_ENABLED: 'COMPANY_BRANCH_ALREADY_ENABLED',
    FAILED_TO_ENABLE_COMPANY_BRANCH: 'FAILED_TO_ENABLE_COMPANY_BRANCH',
    COMPANY_BRANCH_ALREADY_EXISTS: 'COMPANY_BRANCH_ALREADY_EXISTS'
};
