export const COUNTRY_CONSTANT = {
    ALL_COUNTRY_FETCH_SUCCESS: 'ALL_COUNTRY_FETCH_SUCCESS',
    FAILED_TO_FETCH_ALL_COUNTRY: 'FAILED_TO_FETCH_ALL_COUNTRY',
    COUNTRY_DETAIL_BY_COUNTRY_CODE_FETCH_SUCCESS: 'COUNTRY_DETAIL_BY_COUNTRY_CODE_FETCH_SUCCESS',
    FAILED_TO_FETCH_COUNTRY_DETAIL_BY_COUNTRY_CODE: 'FAILED_TO_FETCH_COUNTRY_DETAIL_BY_COUNTRY_CODE',
    FAILED_TO_FETCH_STATES_BY_COUNTRY_CODE: 'FAILED_TO_FETCH_STATES_BY_COUNTRY_CODE',
    FAILED_TO_FETCH_STATE_DETAIL_BY_ID: 'FAILED_TO_FETCH_STATE_DETAIL_BY_ID',
    COUNTRY_NOT_FOUND: 'COUNTRY_NOT_FOUND',
    STATES_BY_COUNTRY_CODE_FETCH_SUCCESS: 'STATES_BY_COUNTRY_CODE_FETCH_SUCCESS',
    STATE_DETAIL_BY_ID_FETCH_SUCCESS: 'STATE_DETAIL_BY_ID_FETCH_SUCCESS'
};
