export const EDUCATION_CONSTANT = {
    SUCCESSFULLY_CREATED_EDUCATION: 'SUCCESSFULLY_CREATED_EDUCATION',
    SUCCESSFULLY_FETCHED_EDUCATION: 'SUCCESSFULLY_FETCHED_EDUCATION',
    EDUCATION_NOT_FOUND: 'EDUCATION_NOT_FOUND',
    SUCCESSFULLY_UPDATED_EDUCATION: 'SUCCESSFULLY_UPDATED_EDUCATION',
    EDUCATION_DELETED: 'EDUCATION_DELETED'
};
