export const EXPERIENCE_CONSTANT = {
    SUCCESSFULLY_CREATED_EXPERIENCE: 'SUCCESSFULLY_CREATED_EXPERIENCE',
    SUCCESSFULLY_FETCHED_EXPERIENCE: 'SUCCESSFULLY_FETCHED_EXPERIENCE',
    EXPERIENCE_NOT_FOUND: 'EXPERIENCE_NOT_FOUND',
    SUCCESSFULLY_UPDATED_EXPERIENCE: 'SUCCESSFULLY_UPDATED_EXPERIENCE',
    EXPERIENCE_DELETED: 'EXPERIENCE_DELETED'
};
