export const FEATURES_CONSTANT = {
    FEATURES_NOT_FOUND: 'FEATURES_NOT_FOUND',
    SUBSCRIPTION_TYPE_FEATURE_FETCHED_FAILED: 'SUBSCRIPTION_TYPE_FEATURE_FETCHED_FAILED',
    SUBSCRIPTION_TYPE_NOT_FOUND: 'SUBSCRIPTION_TYPE_NOT_FOUND',
    ALL_FEATURES_FETCHED_SUCCESSFULLY: 'ALL_FEATURES_FETCHED_SUCCESSFULLY',
    SUBSCRIPTION_TYPE_FEATURES_FETCHED_SUCCESSFULLY: 'SUBSCRIPTION_TYPE_FEATURES_FETCHED_SUCCESSFULLY'
};
