export const LANGUAGE_CONSTANT = {
    SUCCESSFULLY_CREATED_LANGUAGE: 'SUCCESSFULLY_CREATED_LANGUAGE',
    SUCCESSFULLY_FETCHED_LANGUAGE: 'SUCCESSFULLY_FETCHED_LANGUAGE',
    LANGUAGE_NOT_FOUND: 'LANGUAGE_NOT_FOUND',
    SUCCESSFULLY_UPDATED_LANGUAGE: 'SUCCESSFULLY_UPDATED_LANGUAGE',
    LANGUAGE_DELETED: 'LANGUAGE_DELETED',
    FAILED_TO_CREATE_LANGUAGE: 'FAILED_TO_CREATE_LANGUAGE',
    FAILED_TO_UPDATE_LANGUAGE: 'FAILED_TO_UPDATE_LANGUAGE',
    LANGUAGE_ALREADY_CREATED: 'LANGUAGE_ALREADY_CREATED'
};
