export const LEAVE_APPLICATION_CONSTANT = {
    UNABLE_TO_CREATE_LEAVE_APPLICATION: 'UNABLE_TO_CREATE_LEAVE_APPLICATION',
    UNABLE_TO_FIND_LEAVE_APPLICATION: 'UNABLE_TO_FIND_LEAVE_APPLICATION',
    NEW_LEAVE_APPLICATION_CREATED: 'NEW_LEAVE_APPLICATION_CREATED',
    ALL_LEAVE_APPLICATIONS_FETCHED: 'ALL_LEAVE_APPLICATIONS_FETCHED',
    LEAVE_APPLICATION_DETAIL_FOUND: 'LEAVE_APPLICATION_DETAIL_FOUND',
    LEAVE_APPLICATION_UPDATED: 'LEAVE_APPLICATION_UPDATED',
    LEAVE_APPLICATION_STATUS_UPDATED: 'LEAVE_APPLICATION_STATUS_UPDATED',
    LEAVE_APPLICATION_DELETED: 'LEAVE_APPLICATION_DELETED',
    LEAVE_APPLICATION_ACCEPTED: 'LEAVE_APPLICATION_ACCEPTED',
    SIGNATURE_IS_REQUIRED: 'SIGNATURE_IS_REQUIRED',
    STATUS_IS_REQUIRED: 'STATUS_IS_REQUIRED'
};
