export const OC_CONSTANT = {
    GROUP_LIST_FETCHED_SUCCESSFULLY: 'GROUP_LIST_FETCHED_SUCCESSFULLY',
    USER_ADDED_TO_GROUP: 'USER_ADDED_TO_GROUP',
    USER_REGISTERED_SUCCESSFULLY: 'USER_REGISTERED_SUCCESSFULLY'
};
