export const OC_CONSTANT = {
    GROUP_LIST_FETCHED_SUCCESSFULLY: 'GROUP_LIST_FETCHED_SUCCESSFULLY',
    USER_ADDED_TO_GROUP: 'USER_ADDED_TO_GROUP',
    USER_REGISTERED_SUCCESSFULLY: 'USER_REGISTERED_SUCCESSFULLY',
    UNABLE_TO_REGISTER_USER_IN_OC: 'Unable to register user in oracle bucket cloud',
    USER_ALREADY_REGISTERED_WITH_THIS_EMAIL: 'User with the same email already exists'
};
