export const ORGANIZATION_UNIT_CONSTANT = {
    UNABLE_TO_CREATE_ORGANIZATION_UNIT: 'UNABLE_TO_CREATE_ORGANIZATION_UNIT',
    UNABLE_TO_RETRIEVE_ORGANIZATION_UNIT: 'UNABLE_TO_RETRIEVE_ORGANIZATION_UNIT',
    ORGANIZATION_UNITS_NOT_FOUND: 'ORGANIZATION_UNITS_NOT_FOUND',
    UNABLE_TO_UPDATE_ORGANIZATION_UNIT: 'UNABLE_TO_UPDATE_ORGANIZATION_UNIT',
    CANNOT_ENABLE_ORGANIZATION_UNIT: 'CANNOT_ENABLE_ORGANIZATION_UNIT',
    CANNOT_DELETE_ORGANIZATION_UNIT: 'CANNOT_DELETE_ORGANIZATION_UNIT',
    NEW_ORGANIZATION_UNIT_CREATED: 'NEW_ORGANIZATION_UNIT_CREATED',
    ORGANIZATION_UNIT_RETRIEVED: 'ORGANIZATION_UNIT_RETRIEVED',
    ALL_ORGANIZATION_UNIT_RETRIEVED: 'ALL_ORGANIZATION_UNIT_RETRIEVED',
    ORGANIZATION_UNIT_UPDATED: 'ORGANIZATION_UNIT_UPDATED',
    ORGANIZATION_UNIT_NOT_FOUND: 'ORGANIZATION_UNIT_NOT_FOUND',
    ORGANIZATION_UNIT_ENABLED: 'ORGANIZATION_UNIT_ENABLED',
    ORGANIZATION_UNIT_DELETED: 'ORGANIZATION_UNIT_DELETED'
};
