export const ORGANIZATION_CONSTANT = {
    ORGANIZATIONS_NOT_FOUND: 'ORGANIZATIONS_NOT_FOUND',
    FAILED_TO_UPDATE_ORGANIZATION: 'FAILED_TO_UPDATE_ORGANIZATION.',
    COMPANY_NAME_HAS_ALREADY_BEEN_REGISTERED: 'COMPANY_NAME_HAS_ALREADY_BEEN_REGISTERED'
};
