export const ORGANIZATION_STAFFING_CONSTANT = {
    NEW_STAFFING_CREATED: 'NEW_STAFFING_CREATED',
    STAFFING_NOT_CREATED: 'STAFFING_NOT_CREATED',
    ORGANIZATION_UNIT_STAFFING_RETRIEVED: 'ORGANIZATION_UNIT_STAFFING_RETRIEVED',
    STAFFING_RECORD_NOT_FOUND: 'STAFFING_RECORD_NOT_FOUND',
    ALL_STAFFING_RETRIEVED: 'ALL_STAFFING_RETRIEVED',
    STAFFING_RETRIEVED: 'STAFFING_RETRIEVED',
    STAFFING_RECORD_UPDATED: 'STAFFING_RECORD_UPDATED',
    UNABLE_TO_UPDATE_STAFFING: 'UNABLE_TO_UPDATE_STAFFING',
    STAFFING_RECORD_DELETED: 'STAFFING_RECORD_DELETED',
    UNABLE_TO_DELETE_STAFFING: 'UNABLE_TO_DELETE_STAFFING',
    ORGANIZATION_STAFFING_ENABLED: 'ORGANIZATION_STAFFING_ENABLED',
    UNABLE_TO_ENABLE_STAFFING: 'UNABLE_TO_ENABLE_STAFFING',
    ORGANIZATION_STAFFING_NOT_FOUND: 'ORGANIZATION_STAFFING_NOT_FOUND'
};
