export const ORGANIZATION_CONSTANT = {
    ORGANIZATIONS_NOT_FOUND: 'ORGANIZATIONS_NOT_FOUND',
    FAILED_TO_UPDATE_ORGANIZATION: 'FAILED_TO_UPDATE_ORGANIZATION.',
    COMPANY_NAME_HAS_ALREADY_BEEN_REGISTERED: 'COMPANY_NAME_HAS_ALREADY_BEEN_REGISTERED',
    ORGANIZATION_CREATED: 'ORGANIZATION_CREATED',
    ORGANIZATION_UPDATED: 'ORGANIZATION_UPDATED',
    ALL_ORGANIZATIONS_NAME_FETCHED: 'ALL_ORGANIZATIONS_NAME_FETCHED',
    ORGANIZATION_FOUND: 'ORGANIZATION_FOUND'
};
