export const PARTICIPANT_CONSTANT = {
    PARTICIPANT_ADDED: 'PARTICIPANT_ADDED',
    PARTICIPANT_ALREADY_EXIST: 'PARTICIPANT_ALREADY_EXIST',
    PARTICIPANT_LIST_FETCHED: 'PARTICIPANT_LIST_FETCHED',
    PARTICIPANT_NOT_FOUND: 'PARTICIPANT_NOT_FOUND'
};
