export const PROJECT_CONSTANT = {
    PROJECT_NAME_CONFLICT: 'PROJECT_ALREADY_EXIST',
    UNABLE_TO_CREATE_PROJECT: 'UNABLE_TO_CREATE_PROJECT',
    NEW_PROJECT_CREATED: 'NEW_PROJECT_CREATED',
    ALL_PROJECT_RETRIEVED: 'ALL_PROJECT_RETRIEVED',
    PROJECT_RECORDS_NOT_FOUND: 'PROJECT_RECORDS_NOT_FOUND',
    UNABLE_TO_UPDATE_PROJECT: 'UNABLE_TO_UPDATE_PROJECT',
    PROJECT_RECORD_UPDATED: 'PROJECT_RECORD_UPDATED',
    UNABLE_TO_DELETE_PROJECT: 'UNABLE_TO_DELETE_PROJECT',
    PROJECT_DELETE_SUCCESS: 'PROJECT_DELETED_SUCCESS'
};
