export const PROJECT_CONSTANT = {
    PROJECT_CREATED: 'PROJECT_CREATED',
    PROJECT_ALREADY_EXIST: 'PROJECT_ALREADY_EXIST',
    PROJECT_LIST_FETCHED: 'PROJECT_LIST_FETCHED',
    PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND'
};
