export const REPORT_ISSUE_CONSTANT = {
    SUCCESSFULLY_CREATED_ISSUE_REPORT: 'SUCCESSFULLY_CREATED_ISSUE_REPORT',
    SUCCESSFULLY_FETCHED_ALL_ISSUE: 'SUCCESSFULLY_FETCHED_ALL_ISSUE',
    SUCCESSFULLY_APPROVED_BY_SUPER_ADMIN: 'SUCCESSFULLY_APPROVED_BY_SUPER_ADMIN',
    SUCCESSFULLY_REJECTED_BY_SUPER_ADMIN: 'SUCCESSFULLY_REJECTED_BY_SUPER_ADMIN',
    COMPANY_NOT_REGISTERED: 'COMPANY_NOT_REGISTERED'
};
