export const SKILL_CONSTANT = {
    SUCCESSFULLY_CREATED_SKILL: 'SUCCESSFULLY_CREATED_SKILL',
    SUCCESSFULLY_FETCHED_SKILL: 'SUCCESSFULLY_FETCHED_SKILL',
    SKILL_NOT_FOUND: 'SKILL_NOT_FOUND',
    SUCCESSFULLY_UPDATED_SKILL: 'SUCCESSFULLY_UPDATED_SKILL',
    SKILL_DELETED: 'SKILL_DELETED',
    FAILED_TO_CREATE_SKILL: 'FAILED_TO_CREATE_SKILL',
    FAILED_TO_UPDATE_SKILL: 'FAILED_TO_UPDATE_SKILL',
    SKILL_ALREADY_CREATED: 'SKILL_ALREADY_CREATED'
};
