export const TRAVEL_PERMIT_CONSTANT = {
    UNABLE_TO_CREATE_TRAVEL_PERMIT: 'UNABLE_TO_CREATE_TRAVEL_PERMIT',
    UNABLE_TO_FIND_TRAVEL_PERMIT: 'UNABLE_TO_FIND_TRAVEL_PERMIT',
    NEW_TRAVEL_PERMIT_CREATED: 'NEW_TRAVEL_PERMIT_CREATED',
    ALL_TRAVEL_PERMITS_FETCHED: 'ALL_TRAVEL_PERMITS_FETCHED',
    TRAVEL_PERMIT_DETAIL_FOUND: 'TRAVEL_PERMIT_DETAIL_FOUND',
    TRAVEL_PERMIT_UPDATED: 'TRAVEL_PERMIT_UPDATED',
    TRAVEL_PERMIT_STATUS_UPDATED: 'TRAVEL_PERMIT_STATUS_UPDATED',
    TRAVEL_PERMIT_DELETED: 'TRAVEL_PERMIT_DELETED',
    TRAVEL_PERMIT_ACCEPTED: 'TRAVEL_PERMIT_ACCEPTED',
    SIGNATURE_IS_REQUIRED: 'SIGNATURE_IS_REQUIRED',
    STATUS_IS_REQUIRED: 'STATUS_IS_REQUIRED',
    UNABLE_TO_UPDATE_TRAVEL_PERMIT: 'UNABLE_TO_UPDATE_TRAVEL_PERMIT'
};
