export const USER_MAPPING_CONSTANT = {
    USER_MAPPING_ADDED: 'USER_MAPPING_ADDED',
    USER_MAPPING_ALREADY_EXIST: 'USER_MAPPING_ALREADY_EXIST',
    USER_MAPPING_LIST_FETCHED: 'USER_MAPPING_LIST_FETCHED'
};
