export const VERIFICATION_CONSTANT = {
    USER_ALREADY_ACCEPTED_THIS_REQUEST: 'USER_ALREADY_ACCEPTED_THIS_REQUEST',
    INVALID_REQUEST: 'INVALID_REQUEST',
    VERIFICATION_DETAILS_FOUND: 'VERIFICATION_DETAILS_FOUND',
    INVALID_TOKEN: 'INVALID_TOKEN'
};
