export enum FEATURE_IDENTIFIER {
    MANAGE_ALL_USER = 'manage-all-user',
    CHANGE_USER_PASSWORD = 'change-user-password',
    USER_ACTIVITY = 'user-activity',
    PERSONAL_DETAIL = 'personal-detail',
    ORGANIZATION_DETAIL = 'organization-detail',
    ORGANIZATION_UNIT = 'organization-unit',
    ORGANIZATION_STAFFING = 'organization-staffing',
    ORGANIZATION_USER = 'organization-user',
    BLOCKCHAIN_HISTORY = 'blockchain-history',
    MANAGE_BLOCKED_COMPANY_USERS = 'manage-blocked-company-user',
    OC_GROUP = 'oracle-group',
    OC_USER = 'oracle-user',
    APPLICATION_LOGS = 'application-logs',
    PROJECT = 'project',
    PROJECT_DETAILS = 'project-details',
    PROJECT_PURPOSE = 'project-purpose',
    MODEL_VERSION = 'model-version',
    MODEL_REVIEWS = 'model-reviews',
    MODEL_MONITORING = 'model-monitoring',
    BC_NODE_INFO = 'bc-node-info'
}
