import { ApiProperty } from '@nestjs/swagger';
import { IProjectVersion } from '../../project-version/interfaces/project-version.interface';
import { IProject } from '../../project/interfaces/project.interface';
import { IExp } from '../interfaces/ai-model.interface';

export class VersionLogAllExpResponseDto {
    @ApiProperty({
        example: '62b1798d6778381f09a82d29',
        description: "Id of the Ai Model's experiment",
        format: 'string'
    })
    _id: string;

    @ApiProperty({
        example: 'exp_0',
        description: 'Name of experiment',
        format: 'string'
    })
    expNo: string;

    @ApiProperty({
        example: '60e6fe33d27e2133c485513b',
        description: 'Id of version',
        format: 'string'
    })
    version: string;

    @ApiProperty({
        example: '60e6fe33d27e2133c485513b',
        description: 'Id of version',
        format: 'string'
    })
    project: string;

    @ApiProperty({
        example: '62b1798d6778381f09a82d29',
        description: "Id of the Ai Model's experiment generated by lean function",
        format: 'string'
    })
    id: string;

    @ApiProperty({
        example: new Date(),
        description: 'Experiment created date datetime'
    })
    createdAt: Date;

    @ApiProperty({
        example: new Date(),
        description: 'Experiment updated date datetime'
    })
    updatedAt: Date;
}

export class LogExperimentDetailsResponseDto {
    @ApiProperty({
        example: {
            exp_no: 'exp_0',
            datetime: '06/10/2022, 07:42:17',
            hyperparameters: {
                data_dir: '.',
                learning_rate: '0.0002',
                hidden_size: 64
            },
            epochs: {
                '0': {
                    val_loss: 0.2821283638,
                    train_loss: 0.6317886114,
                    train_acc: 0.8187817931,
                    train_f1_score: 0.8188226819000001,
                    train_precision: 0.8188226819000001,
                    train_recall: 0.8188226819000001,
                    val_accuracy: 0.9153481126
                },
                '1': {
                    val_loss: 0.2175901383,
                    train_loss: 0.2988961935,
                    train_acc: 0.9107999802000001,
                    train_f1_score: 0.9107739925,
                    train_precision: 0.9107739925,
                    train_recall: 0.9107739925,
                    val_accuracy: 0.9331487417000001
                }
            },
            test_metrics: {
                test_accuracy: 0.9466000199000001,
                test_f1_score: 0.9465565085000001,
                test_loss: 0.1765899956,
                test_precision: 0.9465565085000001,
                test_recall: 0.9465565085000001
            }
        },
        description: 'These data retrieved form version log file Path'
    })
    exp: IExp;
}

export class LogExperimentInfoResponseDto {
    @ApiProperty({
        example: '62b1798d6778381f09a82d29',
        description: "Id of the Ai Model's experiment",
        format: 'string'
    })
    _id: string;

    @ApiProperty({
        example: 'exp_0',
        description: 'Name of experiment',
        format: 'string'
    })
    expNo: string;

    @ApiProperty({
        example: {
            _id: '62acf90c5a5a33f87a16866d',
            versionName: 'v1',
            logFilePath: 'https://objectstorage.us-phoenix-1.oraclecloud.com/p/m7FALI7al-Sl00Q6ytFqgKq2iG6O-uC2Nnl0NviFj_5A7yzFRz394FRWdn1iCcvC/n/axutkjfnpof3/b/ds-1/o/TSD/v1/logs',
            logFileVersion: '2.1',
            versionModel: 'http://ml.oracle.com/model/',
            noteBookVersion: '1.7',
            testDataSets: 'http://ml.oracle.com/testdataset/',
            trainDataSets: 'http://ml.oracle.com/traindataaset/',
            artifacts: 'http://ml.oracle.com/artificats/',
            codeRepo: 'http://git.com/michael/project-name/',
            codeVersion: '1.2.1',
            comment: 'Test12344',
            versionStatus: 'PENDING',
            status: true,
            createdBy: '62a1c241d7463e3052f5e8cd',
            project: '62acf8345a5a33f87a168632',
            createdAt: '2022-06-17T21:58:36.473Z',
            updatedAt: '2022-06-17T21:58:36.473Z'
        },
        description: 'Log experiment version details',
        format: 'object'
    })
    version: IProjectVersion;

    @ApiProperty({
        example: { _id: '62acfb388238a142968b43cb', name: 'new project' },
        description: 'Log experiment project details',
        format: 'object'
    })
    project: IProject;

    @ApiProperty({
        example: new Date(),
        description: 'Experiment created date'
    })
    createdAt: Date;

    @ApiProperty({
        example: new Date(),
        description: 'Experiment updated date'
    })
    updatedAt: Date;
}

export class DeleteTempOracleDataHashDto {
    @ApiProperty({
        example: '62f33214dee9e736a402285a',
        description: 'Id of hash'
    })
    _id: string;

    @ApiProperty({
        example: '4dc9b1ae052430c635a8d2eef22b602e44472f19e87981f81c27bcab39f00020',
        description: 'Hash of oracle data'
    })
    hash: string;

    @ApiProperty({
        example: new Date(),
        description: 'Hash created date'
    })
    createdAt: Date;

    @ApiProperty({
        example: new Date(),
        description: 'Hash updated date'
    })
    updatedAt: Date;
}

export class ArtifactModelResponseDto {
    @ApiProperty({
        example: '63028eb140da36cbb7ab8d05',
        description: "Id of the Ai artifact's model",
        format: 'string'
    })
    _id: string;

    @ApiProperty({
        example: 'tsd_model_0',
        description: 'Name of artifact model',
        format: 'string'
    })
    modelNo: string;

    @ApiProperty({
        example: '60e6fe33d27e2133c485513b',
        description: 'Id of version',
        format: 'string'
    })
    version: string;

    @ApiProperty({
        example: '60e6fe33d27e2133c485513b',
        description: 'Id of version',
        format: 'string'
    })
    project: string;

    @ApiProperty({
        example: '62b1798d6778381f09a82d29',
        description: "Id of the Ai artifact's model generated by lean function",
        format: 'string'
    })
    id: string;

    @ApiProperty({
        example: new Date(),
        description: 'Experiment created date datetime'
    })
    createdAt: Date;

    @ApiProperty({
        example: new Date(),
        description: 'Experiment updated date datetime'
    })
    updatedAt: Date;
}
