#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

added_files=$(git diff --name-only --cached --diff-filter=d)
npx validate-branch-name
npm run prettier:check
npm run prettier:write
npm run lint
git add ${added_files}
